### ISSUE TITLE
Palemoon

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-browser-settings#2]
Just an info:
I have just tried this for **Palemoon** and can confirm that using the same **distribution.ini** in **/usr/lib/palemoon/distribution** works perfectly! :smiley:

**Comment by oberon2007** [comment]
Shall we make a separate package **manjaro-palemoon-settings**? Or how about simply having **manjaro-firefox-settings** install the file to both locations? Or a split package?

**Comment by Kirek** [comment]
We can use the same package, easier to update and if they switch browser the setting will still apply.

**Comment by oberon2007** [comment]
Yes. Great. Or what about a package **manjaro-browser-settings** installing preferences for FF, Palemoon, Chromium and whatever else we find? Chromium just needs a one-liner **skel/.config/chromium/Default/Preferences**

**Comment by Kirek** [comment]
Mmm, maybe we can make manjaro-browser-settings a meta package with dependencies with all browser packages? Or maybe I'm just complicating things...

**Comment by oberon2007** [comment]
I think it could be quite practical and convenient to just keep those few files in a single repo and install them with one package.
If an url changes for example you can simply adjust that in one place.

**Comment by Kirek** [comment]
Let's go with manjaro-browser-settings, I'm renaming the repo too.
